name: Build & Push Docker Images

on:
  push:
    branches: [main, master]
  workflow_run:
    workflows: [backend-test, frontend-test]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pdf-backend:latest -f backend/Dockerfile ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pdf-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pdf-frontend:latest -f frontend/Dockerfile ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pdf-frontend:latest

# Best practices:
# - Build/push запускається лише після успішних тестів.
# - Для rollback — тегуй образи (наприклад, за git commit hash).
# - Для staging — окремий файл з іншими секретами.
# - Не зберігай паролі у відкритому коді.